//! UI layer for OpenWand desktop app.
//!
//! Contains DTOs, services, bridges, and replay. The UI consumes these types,
//! never raw store internals.

pub mod components;
pub mod design_tokens;
pub mod dto;
pub mod governance_actions;
pub mod governance_components;
pub mod governance_state;
pub mod inspector_components;
pub mod inspector_state;
pub mod layout;
pub mod memory_dto;
pub mod memory_service;
pub mod provider_components;
pub mod provider_config;
pub mod replay;
pub mod run_bridge;
pub mod run_dto;
pub mod session_actions;
pub mod session_components;
pub mod service;
pub mod skills_goals_components;
pub mod skills_goals_state;
pub mod task_plan_components;
pub mod task_plan_state;
pub mod workflow_proposal_components;
pub mod workflow_proposal_state;
pub mod workflow_readiness_components;
pub mod workflow_readiness_state;
pub mod workflow_execution_components;
pub mod workflow_execution_state;
pub mod workflow_action_routing_components;
pub mod workflow_action_routing_state;
pub mod workflow_action_outcome_components;
pub mod workflow_action_outcome_state;
pub mod workflow_reconciliation_components;
pub mod workflow_reconciliation_state;
pub mod workflow_continuation_components;
pub mod workflow_continuation_state;
pub mod workflow_routing_readiness_components;
pub mod workflow_routing_readiness_state;
pub mod workflow_next_action_review_components;
pub mod workflow_next_action_review_state;
pub mod workflow_next_action_routing_components;
pub mod workflow_next_action_routing_state;
pub mod workflow_loop_controller_components;
pub mod workflow_loop_controller_state;
pub mod workflow_command_composer_components;
pub mod workflow_command_composer_state;
pub mod workflow_command_review_components;
pub mod workflow_command_review_state;
pub mod workflow_manual_result_components;
pub mod workflow_manual_result_state;

pub use dto::{CreateSessionRequest, UiMessage, UiMessageRole, UiSessionSummary, UiSessionView};
pub use memory_dto::{UiFilteredMemoryPanel, UiMemoryPanelRow, UiMemoryPanelSummary};
pub use replay::UiTimelineItem;
pub use run_dto::{UiRunEvent, UiRunState, UiRunStatus};
pub use service::{UiServiceError, UiSessionService};
pub mod workflow_manual_result_review_state;
pub mod workflow_manual_result_review_components;
pub mod workflow_manual_result_reconciliation_readiness_state;
pub mod workflow_manual_result_reconciliation_readiness_components;
pub mod workflow_manual_result_reconciliation_gate_state;
pub mod workflow_manual_result_reconciliation_gate_components;
pub mod workflow_operator_console_state;
pub mod workflow_operator_console_components;
pub mod workflow_evidence_chain_inspector_state;
pub mod workflow_evidence_chain_inspector_components;
pub mod workflow_external_attestation_state;
pub mod workflow_external_attestation_components;
pub mod workflow_verification_readiness_state;
pub mod workflow_verification_readiness_components;
pub mod workflow_audit_packet_review_state;
pub mod workflow_audit_packet_review_components;
pub mod workflow_audit_packet_distribution_state;
pub mod workflow_audit_packet_distribution_components;
