//! Desktop workflow run request DTO.
//!
//! Contains ONLY what the desktop UI knows: record IDs and an idempotency key.
//! Does NOT import backend workflow execution types, gates, or evaluators.
//! The service layer resolves hashes from loaded records.
//!
//! Authority boundary: this module imports NO backend crates.
//! It performs no persistence, executes no tools, evaluates no gates,
//! and creates no workflow records.

use serde::{Deserialize, Serialize};

/// Request to initiate a workflow run from the desktop UI.
///
/// The desktop constructs this from inspector signal data (loaded IDs).
/// The service layer loads the full records, extracts hashes, and passes
/// them through the execution gate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowRunRequest {
    /// Readiness record ID to execute from.
    pub readiness_id: String,
    /// Proposal record ID.
    pub proposal_id: String,
    /// Proposal review record ID.
    pub proposal_review_id: String,
    /// Idempotency key (generated by caller, typically timestamp-based).
    pub idempotency_key: String,
    /// Who is requesting (always "desktop" for UI-initiated runs).
    pub requested_by: String,
}

/// Lifecycle state of a desktop-initiated workflow run request.
///
/// Honest representation of what happened:
/// - `Idle`: no request has been made
/// - `Pending`: request submitted, awaiting gate evaluation
/// - `Created`: gate passed, run record created and saved
/// - `Blocked`: gate evaluation returned blocked (predicates failed)
/// - `Failed`: error occurred during request processing
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WorkflowRunRequestState {
    Idle,
    Pending,
    Created {
        execution_id: String,
        status: String,
        stage_count: usize,
        predicates_passed: usize,
        predicates_total: usize,
    },
    Blocked {
        reason: String,
    },
    Failed {
        error: String,
    },
}

impl Default for WorkflowRunRequestState {
    fn default() -> Self {
        Self::Idle
    }
}

impl WorkflowRunRequestState {
    /// Whether this state represents a terminal outcome.
    pub fn is_terminal(&self) -> bool {
        matches!(self, Self::Created { .. } | Self::Blocked { .. } | Self::Failed { .. })
    }

    /// Whether this state indicates the request is in flight.
    pub fn is_pending(&self) -> bool {
        matches!(self, Self::Pending)
    }

    /// Human-readable summary for status display.
    pub fn status_label(&self) -> &str {
        match self {
            Self::Idle => "No workflow run requested",
            Self::Pending => "Requesting workflow run...",
            Self::Created { .. } => "Workflow run created",
            Self::Blocked { .. } => "Workflow run blocked",
            Self::Failed { .. } => "Workflow run request failed",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn request_state_idle_is_not_terminal() {
        assert!(!WorkflowRunRequestState::Idle.is_terminal());
        assert!(!WorkflowRunRequestState::Idle.is_pending());
    }

    #[test]
    fn request_state_pending_is_not_terminal() {
        assert!(WorkflowRunRequestState::Pending.is_pending());
        assert!(!WorkflowRunRequestState::Pending.is_terminal());
    }

    #[test]
    fn request_state_created_is_terminal() {
        let s = WorkflowRunRequestState::Created {
            execution_id: "wfx_1".into(),
            status: "running".into(),
            stage_count: 3,
            predicates_passed: 5,
            predicates_total: 5,
        };
        assert!(s.is_terminal());
        assert!(!s.is_pending());
    }

    #[test]
    fn request_state_blocked_is_terminal() {
        let s = WorkflowRunRequestState::Blocked { reason: "hash mismatch".into() };
        assert!(s.is_terminal());
    }

    #[test]
    fn request_state_failed_is_terminal() {
        let s = WorkflowRunRequestState::Failed { error: "io error".into() };
        assert!(s.is_terminal());
    }

    #[test]
    fn status_labels_are_descriptive() {
        assert!(WorkflowRunRequestState::Idle.status_label().contains("No"));
        assert!(WorkflowRunRequestState::Pending.status_label().contains("Requesting"));
        let created = WorkflowRunRequestState::Created {
            execution_id: "x".into(), status: "s".into(),
            stage_count: 0, predicates_passed: 0, predicates_total: 0,
        };
        assert!(created.status_label().contains("created"));
    }

    #[test]
    fn request_dto_has_only_ids() {
        let req = WorkflowRunRequest {
            readiness_id: "wrd_1".into(),
            proposal_id: "wpp_1".into(),
            proposal_review_id: "wpr_1".into(),
            idempotency_key: "key_1".into(),
            requested_by: "desktop".into(),
        };
        // Verify no hashes, no execution context, no gate types
        let json = serde_json::to_string(&req).unwrap();
        assert!(json.contains("readiness_id"));
        assert!(json.contains("proposal_id"));
        assert!(!json.contains("hash"));
        assert!(!json.contains("context"));
        assert!(!json.contains("gate"));
    }
}
